---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-auth-service-prod-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    JWT_SECRET: AgCF7JGgCJE9iasmp9E6yHvTejm2f4Vg5Dhq5eo2ZJIO/QCG0ARSEKFDPaUTiMGhrAKH23tfshICIdkcKsaS3yj2xTpDsbgJNhDP0jd2GDLlhD1OUAPMF+v4SKx8eBvuOyt37atjMfyU6OufCrD2Uwk51rwEYyAwcYTLwJoXqRTIOgh0temJPjvMjpcCzW5nqEtsqkYwBPHj1uaPzBHzkHH4FoVCkuu5HE/I76UiKOVkCukBzwFBDK4PCQQD2ldRtb/ZDHhhEHgiP7T5D2HBY/qM/34T7AcnFONQwjKZU+jh4Xw5kWQEBsfGvsjwfdPzFLZUFBP8QfkQXnORG0JPPwKxnId+35ci+fk0I5op37WTmr7iLTh3jMJVcJ1HmaMPA7boLl61xJX8Z+2uXOQE6C3c0/6bEEsmwuZt8ugo6Bl+b2MBBz2Ajp0jyUtvX1eRrFnV3EYC28gqrUkOGJ+KSFLgOBJlC9y+Y0z83L3CZEu0YokoYrm+dGUz1pXyvmfVTwsnopVBqnEQxMUAVm+VQmfkdq2RkO6Polt2oU9yyNxUYNbOdFPx5x6EjSCMDDggs7sbxYUpo96VEATxkOwwYXPdQIM01UHi2MJHjykmb0+XzwrRjGzmcsJtxwXjzjgXbqgWF7qzpruhWu4c2ZGCkZ4P/MoyQCni98vOWQ8BxYwE4rOfDg/bM4sMyIWchZ+z0QH1iXUO498=
  template:
    metadata:
      creationTimestamp: null
      name: sa-auth-service-prod-secrets
      namespace: sa-p8-prod
