apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  JWT_SECRET: "mysecretjwtkey201700936"
  RABBITMQ_URL: "amqp://user:password@localhost:5672"

