apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-gateway.fullname" . }}-sa
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "api-gateway.fullname" . }}-role
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api-gateway.fullname" . }}-rb
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "api-gateway.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "api-gateway.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
