---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-account-service-prod-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBJTEnmWeWFJbC0RSFLfpoSHXg8xTwdG4bLyVPbNBhyODeKHVEpGJ74iiHhBMyL1XGGAnM/Zi/OZSfJvfoQun50UtyhjwgcGI/n3JMq2ziHZH5s/pMM8wkGASMxr0tIybzDqcZYJ4bxJoUiORJEaH/Wfgyykarjv+8XlYfvwG/48mqttXfLWHhKp4xuPsfAuO4XFpJTFj6N7OjjsEv/cJKL33AQy9F9O53Y2JLgWr5KXFsD4OgTYR1mRUxrjQEvvnQFlSlVkAQuy1hBTlfma+dLiMqjBf/OkQr8VXJ/Q/Xu9xupay+fy6uqauX1GxKAaiqyfC3cv1l0100OM3m9L5IBhJdBVCbR6kpXngJxNOcTfk6Sup0mZbZ8h2NQm8x/mCcXlXzs77VBFB3J347ys3CRaQD9O541PL3Lga0OpuLirJGX09/qNQoppEjTCEoGmU9fDf6oPpN2G62ZPxR2zCbJzbLkBNzcLbNZh+WFm2w7wLJNtTNH8UxWVt1nG7/dzS3WQMtARvKe6ainJzKMCHNj/audWsQXH6WLzjGw2iNscj4kloKeO7O+2Ah3FpkgXZyZRDT3Yec9DWgAHAoYIhhPtTYpu4czOLs1Cy4phRjbCNsK84nWTd/2m1T9cy16yuR8UeT/GCNQDx2wftdJ5bzHfqApXrL4eaBe+NGqC2oWFIWLGm9QFaq3WWw+9gou514gUd82r2E=
  template:
    metadata:
      creationTimestamp: null
      name: sa-account-service-prod-secrets
      namespace: sa-p8-prod
