---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-transaction-service-prod-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    API_KEY: AgCDrTDqBbE2NkXa3AfmGkhoHH/AF6yuzfZLCQSLBicoUMa84SpM3eITFJX+7LgxCxu6rMrmu3jnpwfhqC4Wb0tactZS9gfMfLbWTSM6Sakuq5a43n3slC0rnYuJJOnuBVDu91LMSMlF9AxdjJFeSrEv72sEcJh35uoH9BDyYPCL4YJ4ZnW1io4UPZo9dzTNjKCs7Nurn7rOs7+9ms3VA5ArPXg651OBZIIe1mlX8gN+aJ0NfNVh27oseiiSJUKqDmFy/S3Yhy/QDMYVLs4u1xIuhJ1hvisxqn8bXinDk14v8NaJimF02hM2zCABw5LOtzqsgc4N6viLtqaWG9CLVPTSzx1T3sOLBfvm+QLj8kN8AHStbn0jf+7F7yjxVevU1BokbyIkwKscZfBAmymWZ9Or+2dFHU4C6kU0A7Av3jEBrc0/hdyYUsNu6bVh1ZHxc+23pLUvbafb0pT/bwcmeK8UpjHTwHmZQX4AhJ/FPjPZVI/f2uGRpi37S5kPi9gbFeKDaIF2rRtgc1SnIT02Kp1XkCs6WAElbEWWDPwJt7gZ8X7N/2mgEiLqRVkU4pfmBEK61SO4rPU814jMOHKr5vESJvCtkPh58DcysrhdvYC8axHbp8bxL3bpqJhzAJ+o3iazdCJwMvh3dWI3xVINPu4DVRTfQ6ExIxA75yPQ1Q9yzEI+cWGhXUhCa/f0p44eklZHh9sR7kE=
    RABBITMQ_URL: AgAjEM+cLcqCWh6V62BgJVU1BwjKXK+n++GCz2AIpLEkV0cW6h2ULAgCdK4jHqorJOo+ilSb1neXVmjUTXtj8UOSsI3isfsmilNaX6ox60iXneArQCM1EgawUYaoXfciN0spTDtkhoNZm5JjPSJNOV+kqHDPLkpIrTJwGeFzs1UWj0BuIxKhnP/HyJtSc5yOL3L4Q2YT6b8nWzblmVH3rDIivQsvtfHg6CL62tgXaQshqmshYq+Ggnzeyknc5YvPqLTfYZWzSVjvIH5C6wA/ixmBYpimz3LUOy9oVQUkBJz7az2AGV82jTY5V9oFNmaZxVqmWyVxnz9y9dJKSpO5yOLzeUDPdWGzKT79yZpqtKhdKiOAsUc4Cvpqg9p31pf+TDYrB7tu4xI4cXK5T+JPOhRFmV/bWqgcLnoTG6NRwQXzpxoKTYJcqtOncFvOZF/fyO8fW6tFhLbBeSgVg0cUu17Zufw/5osuXmk3hT34mtr4dEccYGGWAiRfxZIu938sKeH/uBA2VYVX6EQkJAMgb5ZRl6+hd8iT7G0O2eV97fABfyGFR9BYBS5daEXH4fi0bXw/l4M2pqOLXUji2Sokb+gRfC6BJufOShYXegU0vorBijlU4S/LtYxZB7e5U2ijd29DVcgcoTCXftfXoaI0oVTmG/rqh54PKwiH0c9upRL3Lv+B8rYvCAmih4VNS7gJLd9a43+wCNlAuEQ43j9PI26obmjR9AvjSbmEuFZ3U6DEww==
  template:
    metadata:
      creationTimestamp: null
      name: sa-transaction-service-prod-secrets
      namespace: sa-p8-prod
