---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-notification-service-prod-secrets
  namespace: sa-p8-prod
spec:
  encryptedData:
    RABBITMQ_URL: AgBIvgus3lM82YiKk/1ZVRvXy382eLQfnb+NUtgHHdA6VRFCq+W+TUtl0N9Nn0m2xX19mlgV8CiGGggMLIk3TZZp5hVe1cZBx8woO/rf5LpmwjrmD0bigjdyVsc04JetNJG5yVfM5kIcHfvKpvRCJkKdG/KBimNGhtGUS7pf8vmk3Cx5WKs/9mDg//ZqunUdp4a8CQZkQ2M1halRSp11d9VQzQhzJQFw4tPgqPWvfeufFKBf8f9b+0jPIO0pA0RB2DAhiaP9shWbo09nOTtYTP9HHp3Ap4Qo+R2G+o+WrhvJI9HMR1HGaWaXNVkVmj+5RrhW5YKAo2udvBcdolfexH1g82nmsheKJjHFxOi+40dS10eDInkueqmXW4ms15n125Az1HajSh7cQrNseqYXiLx6K9EjLSpuQuEra31Q3gHzwhv9gf3azcutbrGeVTuS6ix/QbPJgl2uf2lzMf6mcndO+GmhtetOq6acVUPVpWwhyx+K2xGlYGl21E1kRFLj/RfrAxXOsT4tSVhi6Sa1Z6V1TlOB9xccA2T19qx+Y6p/YFgFEVHXthSGfDJGhsqUSmq3F7tFKTZklGQgAN/FQYmnANSn5sqnIdNmKCbyJeZunpacQKjWTJ75z2hlN5f7JWrkcm9qun5qrzd+fWua3vqfy1hABISE+7Qb6WBvG0MjOEe45AEpudkNhvuecihSLszskxleLB0WtEB18rSpAOmCTzXc4ulOmaBISZga1klhQw==
    SMTP_PASSWORD: AgCSwnCoW1SFKhidSciWa1j0zFg4lug1UlAcGAtpxSBgK0+sjog0gYnw/r/IN7h68q5PcdTGz9+ZlcG7AlraHHpMTnP5w3+6AAuxByGPEk8D9NTgyF3H7Uc9GuZbVEshLoUXGFUPs+8LBDv5abVONk1mgWxSVlL+0gfjUbsMfnv1tY/mMqy6Epyswd/KuP1XM22VFPo3srj5Kai8rYpVkiKqfzNZ1dztdH1mttb/44toq4RBslEJboiFt8XyWZJ0J+vi0DVwPLcKfUCALI9ifn9uJ8mjlMxxt3khq66mFOjKAy6hctnEkDKauGVDmp3L08YTzNWwwvlOWiP1JBPeEA+3OYohYswawNe9gLXX8AVoQGk12QnmJ/xz8ouZ7aFmdkQSJFcQo5+d6pPPHa0r2696tuaMMOReG0Wlt+/1XsbOd8gu/KA83L/JY8e+M5TY2yO5ZIGspFAK04ioX1kKnZTThuxabXftTZaey1PPwtU9a8NxD+OUOXGBPMWZ7irM8YnuMFtAo2zGoFq2VpAg7Xh6UQXznDO90K3NjcggASotlocRTXj5U9KbqrwcJ12AFK6HQgxyaNDGHrQyJbTzfcX3DSQGhklpt6sjmcvHZfLOFeqWVhsnh7pBiKo561FQeTyfGTMhmFLf/jRon5DT4Wd6nWCcfMsXS7wRkYrPWrx2+y/aLghMWnEL8c4nb2lZcls/xUUrDVs=
  template:
    metadata:
      creationTimestamp: null
      name: sa-notification-service-prod-secrets
      namespace: sa-p8-prod
